server:
  port: 8080
#调试模式  主要是打印spring框架相关的启动日志
debug: false
#跟踪模式
trace: false
#日志配置
logging:
  #日志配置文件路径,如果指定了配置文件路径，则此配置下的其他spring日志配置就不会生效了，因为已经指定了配置文件，则spring的默认配置就不生效了
  config: classpath:logback/logback-spring.xml
#spring配置
spring:
  http:
    encoding:
      #启动字符过滤器
      enabled: true
      charset: UTF-8
  #jpa配置
  jpa:
    #指定数据库类型
    database: MYSQL
    #是否打印sql
    show-sql: true
    #格式化sql
    format-sql: true
    #hibernate配置
    hibernate:
      packagesToScan: com.sp
      #是否根据实体变化自动更新数据库
      ddl-auto: update
      #命名规则
      naming:
        #命名规则
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #数据库方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #session交由spring管理
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  #数据源配置
  datasource:
    #指定连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: Wochenqi!
    # 下面为连接池的补充设置，应用到上面所有数据源中
    #这里配置的是插件,常用的插件有:stat,wall,slf4j
    filters: stat
    # 初始化大小，最小，最大
    initialSize: 5
    #回收空闲连接时，将保证至少有minIdle个连接.
    minIdle: 5
    #连接池中最多支持多少个活动会话
    maxActive: 500
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #检查池中的连接是否仍可用的 SQL 语句,drui会连接到数据库执行该SQL, 如果正常返回，则表示连接可用，否则表示连接不可用
    validationQuery: SELECT 1 FROM DUAL
    #当程序请求连接，池在分配连接时，是否先检查该连接是否有效。(高效)
    testWhileIdle: true
    #程序 申请 连接时,进行连接有效性检查（低效，影响性能）
    testOnBorrow: false
    #程序 返还 连接时,进行连接有效性检查（低效，影响性能）
    testOnReturn: false
    #缓存通过以下两个方法发起的SQL:public PreparedStatement prepareStatement(String sql)
    #public PreparedStatement prepareStatement(String sql,int resultSetType, int resultSetConcurrency)
    poolPreparedStatements: true
    #每个连接最多缓存多少个SQL
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true
    useGlobalDataSourceStat: true
    allow: 127.0.0.1

