spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8080
#日志配置
logging:
  #日志配置文件路径,如果指定了配置文件路径，则此配置下的其他配置就不会生效了，因为已经指定了配置文件，则spring的默认配置就不生效了
  #config: classpath:logback/logback-spring.xml
  #日志级别：trace<debug<info<warn<error
  #日志级别的优先级：包.类>包>组>项目(root)
  #dev日志组
  group:
    dev: com.sp.contoller,com.sp.common.filter,org.springframework
  level:
    #    root: DEBUG
    #配置日志组，指定日志组的日志级别-如果日志组和单独指定包类日志级别对同一个包/类都指定了，则谁配置在后谁生效
    dev: DEBUG
    #配置指定包或类的日志级别
    com.sp.contoller: INFO
    org.springframework.web: DEBUG
    org.hibernate: debug



#调试模式  主要是打印spring框架相关的启动日志
debug: false
#跟踪模式
trace: false
